services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  build_env:
    container_name: build_env
    build:
      context: .
      dockerfile: Dockerfile
    image: build_env
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres?schema=public
    depends_on:
      - db
    command: 'tail -f /dev/null'

volumes:
  db:
